# Generated by LLM Code Graph Compiler
# DO NOT EDIT MANUALLY

# --- Node: CSVParser ---
import pandas as pd

def csv_parser(file_path: str) -> pd.DataFrame:
    """
    Reads a CSV file from disk and returns a DataFrame.
    Node: CSVParser
    """
    df = pd.read_csv(file_path)
    print(f"[CSVParser] Loaded {len(df)} rows from {file_path}")
    return df


# --- Node: DataFilter ---
import pandas as pd

def data_filter(df: pd.DataFrame, condition: str) -> pd.DataFrame:
    """
    Filters rows using pandas query syntax.
    Example condition: "age > 30 and salary < 50000"
    Node: DataFilter
    """
    filtered = df.query(condition)
    print(f"[DataFilter] Applied condition: {condition}")
    return filtered


# --- Node: DataSorter ---
import pandas as pd

def data_sorter(df: pd.DataFrame, by: str, ascending: bool = True) -> pd.DataFrame:
    """
    Sorts DataFrame by column.
    Node: DataSorter
    """
    sorted_df = df.sort_values(by=by, ascending=ascending)
    print(f"[DataSorter] Sorted by {by}, ascending={ascending}")
    return sorted_df


# --- Node: CSVExporter ---
import pandas as pd

def csv_exporter(df: pd.DataFrame, output_path: str) -> str:
    """
    Exports DataFrame to CSV.
    Node: CSVExporter
    """
    df.to_csv(output_path, index=False)
    print(f"[CSVExporter] Exported to {output_path}")
    return output_path


# --- Execution (auto-generated) ---
if __name__ == '__main__':
    out_csv_parser = csv_parser(file_path="data.csv")
    out_data_filter = data_filter(out_csv_parser, condition="age > 25")
    out_data_sorter = data_sorter(out_data_filter, by="age", ascending="True")
    out_csv_exporter = csv_exporter(out_data_sorter, output_path="output.csv")
    print(out_csv_exporter)