# Generated by LLM Code Graph Compiler
# DO NOT EDIT MANUALLY

# --- Node: CSVParser ---
import pandas as pd

def csv_parser(file_path: str) -> pd.DataFrame:
    """
    Reads a CSV file from disk and returns a DataFrame.
    Node: CSVParser
    """
    df = pd.read_csv(file_path)
    print(f"[CSVParser] Loaded {len(df)} rows from {file_path}")
    return df


# --- Node: SQLiteConnector ---
import sqlite3
import pandas as pd

def sqlite_connector(df: pd.DataFrame, db_path: str, table_name: str):
    """
    Stores DataFrame into SQLite and returns connection.
    Node: SQLiteConnector
    """
    conn = sqlite3.connect(db_path)
    df.to_sql(table_name, conn, if_exists="replace", index=False)
    print(f"[SQLiteConnector] Stored table '{table_name}' in {db_path}")
    return conn


# --- Node: QueryEngine ---
import pandas as pd
import sqlite3

def query_engine(conn: sqlite3.Connection, query: str) -> pd.DataFrame:
    """
    Executes SQL query on DBHandle.
    Node: QueryEngine
    """
    df = pd.read_sql_query(query, conn)
    print("[QueryEngine] Query executed")
    return df


# --- Execution (auto-generated) ---
if __name__ == '__main__':
    out_csv_parser = csv_parser(file_path="path/to/csv/file.csv")
    out_sqlite_connector = sqlite_connector(out_csv_parser, db_path="path/to/database.db", table_name="my_table")
    out_query_engine = query_engine(out_sqlite_connector, query="SELECT * FROM my_table")
    print(out_query_engine)