import os
from nodes.registry import NODE_REGISTRY
from core.validator import validate_plan, topological_sort


def _output_var(node_name: str) -> str:
    return f"out_{NODE_REGISTRY[node_name].function_name}"


def auto_glue_code(ordered_nodes: list, edges: list, parameters: dict) -> str:
    predecessor = {}
    for source, target in edges:
        predecessor[target] = source

    lines = []
    lines.append("if __name__ == '__main__':")

    for node_name in ordered_nodes:
        func_name = NODE_REGISTRY[node_name].function_name
        out_var = _output_var(node_name)
        params = parameters.get(node_name, {})

        args = []

        if node_name in predecessor:
            pred = predecessor[node_name]
            args.append(_output_var(pred))

        for key, value in params.items():
            args.append(f'{key}="{value}"')

        arg_str = ", ".join(args)
        lines.append(f"    {out_var} = {func_name}({arg_str})")

    last_var = _output_var(ordered_nodes[-1])
    lines.append(f"    print({last_var})")

    return "\n".join(lines)


def compile_output(plan: dict) -> str:
    is_valid, errors = validate_plan(plan)

    if not is_valid:
        raise ValueError("Invalid plan:\n" + "\n".join(errors))

    nodes = plan.get("nodes", [])
    edges = plan.get("edges", [])
    parameters = plan.get("parameters", {})

    ordered_nodes = topological_sort(nodes, edges)
    glue_code = plan.get("glue_code", "").strip()

    output_parts: list[str] = []

    output_parts.append("# Generated by LLM Code Graph Compiler")
    output_parts.append("# DO NOT EDIT MANUALLY\n")

    for node_name in ordered_nodes:
        node = NODE_REGISTRY[node_name]
        template_path = node.template_path

        if not os.path.exists(template_path):
            raise FileNotFoundError(
                f"Template not found for node '{node_name}': {template_path}"
            )

        with open(template_path, "r", encoding="utf-8") as f:
            template_code = f.read()

        output_parts.append(f"# --- Node: {node_name} ---")
        output_parts.append(template_code.strip() + "\n")
        output_parts.append("")

    if glue_code:
        output_parts.append("# --- Execution (LLM-generated) ---")
        output_parts.append(glue_code)
    else:
        output_parts.append("# --- Execution (auto-generated) ---")
        output_parts.append(auto_glue_code(ordered_nodes, edges, parameters))

    return "\n".join(output_parts)


def write_output(code: str, path: str = "output/app.py") -> None:
    os.makedirs("output", exist_ok=True)

    with open(path, "w", encoding="utf-8") as f:
        f.write(code)

    with open("output/requirements.txt", "w", encoding="utf-8") as f:
        f.write("flask\npandas\n")

    print(f"Emitted: {path}")
    print("Emitted: output/requirements.txt")