import os
from nodes.registry import NODE_REGISTRY


def compile_output(plan: dict) -> str:
    from core.validator import topological_sort
    nodes = plan.get("nodes", [])
    edges = plan.get("edges", [])
    ordered_nodes = topological_sort(nodes, edges)
    glue_code = plan.get("glue_code", "")

    output_parts: list[str] = []

    # Header
    output_parts.append("# Generated by LLM Code Graph Compiler")
    output_parts.append("# DO NOT EDIT MANUALLY\n")

    # Load each node template
    for node_name in ordered_nodes:
        node = NODE_REGISTRY[node_name]
        template_path = node.template_path

        if not os.path.exists(template_path):
            raise FileNotFoundError(
                f"Template not found for node '{node_name}': {template_path}"
            )

        with open(template_path, "r", encoding="utf-8") as f:
            template_code = f.read()

        output_parts.append(f"# --- Node: {node_name} ---")
        output_parts.append(template_code)
        output_parts.append("")

    # Append glue code
    output_parts.append("# --- Execution ---")
    output_parts.append(glue_code)

    return "\n".join(output_parts)


def write_output(code: str, path: str = "output/app.py") -> None:
    os.makedirs("output", exist_ok=True)

    with open(path, "w", encoding="utf-8") as f:
        f.write(code)

    # Minimal requirements file
    with open("output/requirements.txt", "w", encoding="utf-8") as f:
        f.write("flask\npandas\n")

    print(f"Emitted: {path}")
    print("Emitted: output/requirements.txt")